DELETE FROM Year;
delete from sqlite_sequence where name='Year';
INSERT INTO Year (LASTMODIFIED, DELETED, NUMBER) VALUES(date('now'), 0, 2018);
INSERT INTO Year (LASTMODIFIED, DELETED, NUMBER) VALUES(date('now'), 0, 2019);
INSERT INTO Year (LASTMODIFIED, DELETED, NUMBER) VALUES(date('now'), 0, 2020);
INSERT INTO Year (LASTMODIFIED, DELETED, NUMBER) VALUES(date('now'), 0, 2021);
